import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'theme.dart';
import 'screens/home_router_screen.dart';
import 'screens/login_screen.dart';
import 'services/session.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` — see README

// Must be a top-level function. Handles a push notification that arrives
// while the app is fully closed/in background.
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  await Session.instance.init();
  runApp(const CustomerApp());
}

class CustomerApp extends StatelessWidget {
  const CustomerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'E-Bike Customer',
      debugShowCheckedModeBanner: false,
      theme: buildAppTheme(),
      home: Session.instance.isLoggedIn ? const HomeRouterScreen() : const LoginScreen(),
    );
  }
}
